### PR TITLE
api key set to default and server updated for configurations

### PR DESCRIPTION
**Pull request by SamuelGHill**

### CODE REVIEW

**Comment by SamuelGHill** [comment]
Updated mailchimp to include the unique server request in the `stepzen.config.json` and added a general `lists` endpoint so developers can see the lists they want to individually query.

Resolves --> https://github.com/steprz/stepzen-schemas/issues/26

**Review by remotesynth — CHANGES_REQUESTED** [review]
This doesn't work. It generates the error:

```
Error: Unknown type "List". Did you mean "Lists" or "Int"?

    Unknown type "List". Did you mean "Lists" or "Int"?

    Unknown type "MailChimpList". Did you mean "MailChimpLists"?

    Unknown type "MailChimpList". Did you mean "MailChimpLists"?
```

The issue seems to be, looking at the code, that you have types that don't exist. For example MailChimpList doesn't exist in the schema but MailChimpLists does.  Please be sure to test these changes before we commit them.

**Comment by fakedarren** [comment]
@SamuelGHill let's discuss some workflow options,  closing for now

**Comment by SamuelGHill** [comment]
Reopening @fakedarren what should we discuss to get this error resolved? I tested this locally and its good to go for mailchimp.

**Comment by fakedarren** [comment]
Hi @SamuelGHill, we clearly need automated tests.

As it stands, @remotesynth is correct. All those errors still exist in this code. Please see above and address his comments (and you will need to run the formatting script as well)

**Review by remotesynth — APPROVED** [review]

**Pull request merged**
