### PR TITLE
removed interfaces and supplies from schemas

### PR DESCRIPTION
**Pull request by SamuelGHill**

### CODE REVIEW

**Comment by SamuelGHill** [comment]
I did not QA...

1. Contentful (I do not have access to this env.  Who does?)
2. Dev-to

I QA'd but could not get to work...
1. UPS

@carloseberhardt 
QA'd schemas locally.  All are good except the UPS delivery I could not get to return data.  I also removed the duplicates (example --> `delivery.graphql` & `delivery-fedex.graphql` is now just `delivery-fedex.graphql) for blackbox connectors since we do not need to define interfaces in one and pass it to another, which worked. 

@remotesynth 
I did not QA was dev-to with github since I do not have any dev.to articles, which is an indicator that I need to start writing some! But if you could make changes to the dev-to one and also the readme with that one I can handle the other readme's to go along with these schema changes.

**Comment by SamuelGHill** [comment]
Adding in my `index.graphql` to save time for QA --> 

```
schema
  @sdl(
    files: [
      # "shopify/products.graphql"
      # "shopify/orders.graphql"
      # "shopify/customers.graphql"
      # "shopify/extend.graphql"
      #   "twilio/twilio.graphql"
      #   "mailchimp/mailchimp.graphql"
      #   "github/github.graphql"
      #   "eligible/eligible.graphql"
      #   "disqus/disqus.graphql"
      #   "cloudinary/cloudinary.graphql"
      #   "amadeus/flights.graphql"
      #   "algolia/algolia.graphql"
      "airtable/venue.graphql"
      "airtable/event.graphql"
      "airtable/event-venue.graphql"
      # "openweathermap/weatherreport.graphql"
      # "openweathermap/weather-report-owm.graphql"
      # "ups/delivery.graphql"
      # "ups/delivery-ups.graphql"
      # "ip-api/locationIpApi.graphql"
      # "fedex/delivery-fedex.graphql"
      # "holiday/holiday-api.graphql"
      # "wordpress/wordpress.graphql"
    ]
  ) {
  query: Query
}
```

**Comment by remotesynth** [comment]
@SamuelGHill @carloseberhardt ok. Hold on merging this one while I update the devto ones.

**Comment by remotesynth** [comment]
I added my changes to dev-to and devto-github to remove interfaces. @carloseberhardt can you review all the changes?

**Comment by carloseberhardt** [comment]
@SamuelGHill can we close this PR without merging now?

**Comment by SamuelGHill** [comment]
@carloseberhardt Closing now.

**Pull request closed without merging**
